language: node_js
node_js:
  - 8
sudo: required
services:
  - docker
before_install:
  - docker pull selenium/standalone-chrome:latest
before_script:
  - docker run -d --net=host --shm-size=2g selenium/standalone-chrome:latest
script:
  - npm install
  - npm install selenium-server
  - ./node_modules/.bin/selenium-standalone install
  - npm run test
